---
ID: "7c852721-7717-41cf-b729-473859228964"
Parent: "bd320c29-a67e-4b4b-8e79-af5214421ad9"
Template: "b06f7c55-9717-4bfa-86d5-875b2ddac17c"
Path: /sitecore/system/Settings/Foundation/Speedy/Speedy Global Settings
DB: master
SharedFields:
- ID: "5a158a54-b524-483c-a3a0-6e2a5fcc5cbe"
  Hint: EndpointURL
  Value: "http://localhost:3000"
- ID: "af9fa73f-f0a8-4d58-8dea-cb2169147c87"
  Hint: DeferJSLoadForMilliseconds
  Value: 6000
- ID: "f4006c48-6487-43b7-8d65-a3c32c637e29"
  Hint: RemoteFontMap
  Value: |
    { "fontMap": [
        {
          "find": "/Users/sitecore/AppData/Local/fonts/tahoma/",
          "replace": "/-/media/themes/mysite/mysite-theme/fonts/tahoma/"
        },
        {
          "find": "/Users/sitecore/AppData/Local/fonts/fontawesome/",
          "replace": "/-/media/themes/mysite/mysite-theme/fonts/fontawesome/"
        },            
        {
          "find": "content:\"\"",
          "replace": ""
        },
        {
          "find": "content:\"\"",
          "replace": ""
        },
        {
          "find": "url(/C:/-/media/",
          "replace": "url(/-/media/"
        },
        {
          "find": "@font-face{",
          "replace": "@font-face{font-display: swap;"
        }
      ]
    }
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190426T102857Z
    - ID: "3bd89967-8179-41eb-b4d0-30bb21f892fe"
      Hint: RemoteFontsToSwitch
      Value: |
        {"fontFaceSwitch": [
            {
              "find": "font-family:NationalWebExtraBold;",
              "replace": "font-family:NationalWebExtraBold-Critical;"
            },
            {
              "find": "font-family:NationalWeb;",
              "replace": "font-family:NationalWeb-Critical;"
            },
            {
              "find": "font-family:NationalWebExtraBold;",
              "replace": "font-family:NationalWebExtraBold-critical;"
            },
            {
              "find": "font-family:NationalWebMedium;",
              "replace": "font-family:NationalWebMedium-critical;"
            },
            {
              "find": "font-family:NationalWeb;",
              "replace": "font-family:NationalWeb-critical;"
            },
            {
              "find": "font-family:NationalWebBold;",
              "replace": "font-family:NationalWebBold-critical;"
            }
          ]}
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "c86e2356-39db-45c9-9451-5232660b8074"
      Hint: RemoteDuplicatesToRemove
      Value: |
        {
        "removeDuplicates": [
            {
              "find": "@font-face{font-display: swap;font-family:Conv_tahoma;src:url(/-/media/themes/mysite/mysite-theme/fonts/tahoma/tahoma_eot.eot);src:local(\"☺\"),url(/-/media/themes/mysite/mysite-theme/fonts/tahoma/tahoma_woff.woff) format(\"woff\"),url(/-/media/themes/mysite/mysite-theme/fonts/tahoma/tahoma_ttf.ttf) format(\"truetype\"),url(/-/media/themes/mysite/mysite-theme/fonts/tahoma/tahoma_svg.svg) format(\"svg\");font-weight:400;font-style:normal}"
            },
            {
              "find": "@font-face{font-display: swap;src:url(/-/media/themes/mysite/mysite-theme/fonts/tahoma/tahoma_eot.eot);src:local(\"☺\"),url(/-/media/themes/mysite/mysite-theme/fonts/tahoma/tahoma_woff.woff) format(\"woff\"),url(/-/media/themes/mysite/mysite-theme/fonts/tahoma/tahoma_ttf.ttf) format(\"truetype\"),url(/-/media/themes/mysite/mysite-theme/fonts/tahoma/tahoma_svg.svg) format(\"svg\");font-weight:400;font-style:normal}"
            },
            {
              "find":"@font-face{font-display: swap;font-family:FontAwesome;src:url(/-/media/themes/mysite/mysite-theme/fonts/fontawesome/fontawesome-webfont-eot.eot?v=4.7.0);src:url(/-/media/themes/mysite/mysite-theme/fonts/fontawesome/fontawesome-webfont-eot.eot?#iefix&v=4.7.0) format(\"embedded-opentype\"),url(/-/media/themes/mysite/mysite-theme/fonts/fontawesome/fontawesome-webfont-woff2.woff2?v=4.7.0) format(\"woff2\"),url(/-/media/themes/mysite/mysite-theme/fonts/fontawesome/fontawesome-webfont-woff.woff?v=4.7.0) format(\"woff\"),url(/-/media/themes/mysite/mysite-theme/fonts/fontawesome/fontawesome-webfont-ttf.ttf?v=4.7.0) format(\"truetype\"),url(/-/media/themes/mysite/mysite-theme/fonts/fontawesome/fontawesome-webfont-svg.svg?v=4.7.0#fontawesomeregular) format(\"svg\");font-weight:400;font-style:normal}"
            }
          ]
        }
