---
ID: "e25a860e-b060-4aab-9e6b-91546efb08cc"
Parent: "9b00343f-ea68-4ea6-be27-301843b18e36"
Template: "411f24df-bb3e-4741-8dd4-38207b81f5b8"
Path: /sitecore/system/Settings/Foundation/ImageCompression/Image Compression Settings
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "Image Compression Settings - Tiny Png"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200318T124915Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
