---
ID: "76ccc6fd-80db-4d36-95c6-fda2ce6521f5"
Parent: "b06f7c55-9717-4bfa-86d5-875b2ddac17c"
Template: "b06f7c55-9717-4bfa-86d5-875b2ddac17c"
Path: /sitecore/templates/Foundation/Speedy/_SpeedyGlobalSettings/__Standard Values
DB: master
SharedFields:
- ID: "32c93514-942e-4411-a8b1-9432cb055bc1"
  Hint: CookieExpirationDays
  Value: 10
- ID: "4fda48e4-0a51-4aa7-9d98-5008502377e6"
  Hint: DeferCSSLoadForMilliseconds
  Value: 5500
- ID: "6c44f9ab-65f2-4730-87e3-ffda8aec3da5"
  Hint: DeferFallbackForMilliseconds
  Value: 5000
- ID: "af9fa73f-f0a8-4d58-8dea-cb2169147c87"
  Hint: DeferJSLoadForMilliseconds
  Value: 4000
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190426T111214Z
    - ID: "348d98df-86f6-4beb-9b84-2ab946e100c7"
      Hint: CSSFilter
      Value: "media/Base-Themes/Core-Libraries/styles/optimized-min.css=%7Bfilters%3A%20%5B%7Bstart%3A%20%27%2F%2A%21%5Cn%20%2A%20%20Font%20Awesome%204.7.0%20by%20%40davegandy%27%2C%20end%3A%20%27%2F%2A%21%5Cn%20%2A%20FullCalendar%20v3.8.1%27%7D%2C%20%7Bstart%3A%27%2F%2A%21%5Cn%20%2A%20FullCalendar%20v3.8.1%27%2C%20end%3A%20%27%2F%2A%21%20jQuery%20UI%27%7D%20%5D%7D&media/Themes/Habitat-SXA-Sites/Habitat-Home-Basic/styles/optimized-min.css=%5B%7Bstart%3A%20%27%2F%2A%21%20%20%2A%20%20Font%20Awesome%204.7.0%20by%20%40davegandy%27%2C%20end%3A%20%27.container-color-background%7Bbackground%3A%2350a1ab%7D%27%7D%20%5D"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
